10 post api articles articleid comments
laurie60/be-news pull request #9
Opened 2022-07-07 13:44 UTC by laurie60

2022-07-07 14:29 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +  });
The post body should have a key of username and body like {username: "icellusedcars", body: "Never gonna give you up"} Also I would add tests for if the post has missing info like if the username or body is missing

2022-07-07 14:30 UTC, Rayhaan2k9 requested changes
Almost there. Just check my comment :)

2022-07-08 08:15 UTC, karlaferry commented on __tests__/app.test.js
> +    test("400: with comment of invalid input type if input is missing username ", () => {
You also want to test that `body` exists in the post body :) So just make another test that looks like this but this time handle it if `body` is missing.

2022-07-08 08:17 UTC, karlaferry approved these changes
Approving but make sure to add that last test! Also, well done, very nice use of async/await 👏🏼

2022-07-08 09:02 UTC, merged